Validation
Sad1lovbatya/TaskManager pull request #11
Opened 2020-04-16 13:18 UTC by Sad1lovbatya

2020-04-16 13:53 UTC, pn-y requested changes

2020-04-16 13:53 UTC, pn-y commented on app/models/user.rb
> +  validates :email, presence: true, uniqueness: true
Валидации уникальности в приложении *ВСЕГДА* недостаточно.
Добавь валидацию на уровне БД

2020-04-16 14:23 UTC, Sad1lovbatya commented on app/models/user.rb
> +  validates :email, presence: true, uniqueness: true
Учёл, буду знать в следующий раз
Добавил валидацию на уровне БД


у меня возник вопрос, не заходит в консоль рельс(rails c), падает ошибка /bundle_cache/gems/factory_bot-5.1.2/lib/factory_bot/definition_proxy.rb:99:in `method_missing': undefined method 'name' in 'task' factory (NoMethodError)
Did you mean? 'name { "MyString" }' 
Но "{ }" я убрал сам, так как мне ответили на пулл реквест, что их надо убрать, они будут браться из sequence
Я неправильно сделал файл sequence.rb ?

2020-04-16 14:47 UTC, pn-y commented on app/models/user.rb
> +  validates :email, presence: true, uniqueness: true
@Sad1lovbatya в таком случае тебе надо убрать строку которая идет после name, скорее всего

2020-04-16 15:12 UTC, Sad1lovbatya commented on app/models/user.rb
> +  validates :email, presence: true, uniqueness: true
валидация на уровне БД не работала, помогло gem install database_validations, всё проходит
Но создание пользователей и задач в консоли rails c происходит только при добавлении {}

2020-04-16 15:19 UTC, pn-y commented on app/models/user.rb
> +  validates :email, presence: true, uniqueness: true
валидация на уровне БД это уникальный индекс, для этого не нужны гемы.
То как ты описал сиквенсы - пойдет для вызова их внутри тестов.
Но для вызова внутри фабрик - надо описать по другому. Посмотри доку https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md

2020-04-16 15:23 UTC, Sad1lovbatya commented on app/models/user.rb
> +  validates :email, presence: true, uniqueness: true
Спасибо, ознакомплюсь и исправлю

2020-04-16 17:13 UTC, Sad1lovbatya commented on app/models/user.rb
> +  validates :email, presence: true, uniqueness: true
Дописал атрибуты для вызова внутри фабрик
https://github.com/Sad1lovbatya/TaskManager/pull/10

2020-04-16 21:28 UTC, artempartos requested changes

2020-04-16 21:28 UTC, artempartos commented on test/factories/tasks.rb
> +    author_id
author_id и assigned_id надо удалить, это идентификаторы ассоциаций.
Дальше - author {create :user} - это асоциация, в фабрике по умолчанию все ассоциации должны быть { nil } чтобы не было циклических зависимостей, в фабрике нет ассоциации assignee.
Когда тебе нужна таска с автором (с любой ассоциацией) - создай trait, прочитай про них, и добавь в фабрику два трейта - с author и с assignee

2020-04-17 04:46 UTC, Sad1lovbatya commented on test/factories/tasks.rb
> +    author_id
https://github.com/Sad1lovbatya/TaskManager/pull/11 добавил traits для author и assignee

2020-04-17 06:47 UTC, Sad1lovbatya commented on app/models/user.rb
> +  validates :email, presence: true, uniqueness: true
Создал миграцию, прописал там уникальный индекс, добавил в пуллреквест
Или мне нужно было добавить уже в существующую миграцию create_users?

2020-04-17 07:30 UTC, Sad1lovbatya commented on test/factories/tasks.rb
> +    author_id
Получается traits нужны для доступа фабрик к атрибутам users ?

2020-04-17 09:49 UTC, pn-y requested changes

2020-04-17 09:49 UTC, pn-y commented on db/migrate/20200416164418_create_users.rb
> +    add_index :users, :email, unique: true
Это точно работает? Добавление индекса в несуществующее поле несуществующей таблицы.

2020-04-17 11:10 UTC, artempartos requested changes

2020-04-17 11:10 UTC, artempartos commented on test/factories/tasks.rb
> +    expired_at
assignee { nil }
author { nil }
и где трейты под них, где они не пустые?

2020-04-18 16:30 UTC, Sad1lovbatya commented on test/factories/tasks.rb
> +    expired_at
Поправил всё

2020-04-18 18:04 UTC, pn-y requested changes

2020-04-18 18:04 UTC, pn-y commented on test/factories/users.rb
> +    type
Без указания трейта такой фабрикой будут создаваться невалидные данные.

2020-04-18 18:04 UTC, pn-y commented on test/factories/sequence.rb
> +    "date#{n}"
Не стоит пихать строку в колонку с датой

2020-04-18 18:34 UTC, Sad1lovbatya commented on test/factories/users.rb
> +    type
Я правильно понимаю, что я должен все атрибуты занести в каждый trait для users?

2020-04-20 10:45 UTC, pn-y requested changes

2020-04-20 10:45 UTC, pn-y commented on test/factories/sequence.rb
> +    Time.now
Не стоит использовать Time.now https://habr.com/ru/company/at_consulting/blog/266681/

2020-04-20 10:45 UTC, pn-y commented on test/factories/users.rb
> +    type
Не поправлено

2020-04-21 07:25 UTC, Sad1lovbatya reviewed
Убрал type из sequence, для того чтобы он генерировался
Не совсем понимаю, как я должен ещё указать trait, в task определил, в users добавил

2020-04-21 07:25 UTC, Sad1lovbatya commented on test/factories/users.rb
> +    type
Я не понимаю как я должен явно указать трейт, пересмотрел информацию по  factorybot 
( https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md ) b и так не смог понять, почему мои данные будут не валидные

2020-04-21 10:24 UTC, pn-y requested changes

2020-04-21 10:24 UTC, pn-y commented on test/factories/users.rb
> +  end
Так, а теперь типа не хватает.
У тебя сгенерится юзер без типа.

2020-04-21 10:32 UTC, Sad1lovbatya commented on test/factories/users.rb
> +  end
Да, ошибся, добавил заново тип 
c Trait у меня всё в порядке теперь или нет? 
Я немного запутался, по сути trait нужен для удобстава и я могу его не создавать, ошибки возникать не должно?

2020-04-22 13:52 UTC, pn-y commented on test/factories/users.rb
> +  end
>Я немного запутался, по сути trait нужен для удобстава и я могу его не создавать, ошибки возникать не должно?
верно

2020-04-22 13:54 UTC, pn-y requested changes

2020-04-22 13:54 UTC, pn-y commented on test/factories/users.rb
> +    type { "User" }
Такой тип не будет никогда использоваться. Потому что будут использоваться Admin Developer Manager.
Соответственно и `aliases: %i[author assignee]` не верно.
Тебе нужны фабрики admin, developer, manager которые унаследуют аттрибуты юзера, которые ты уже настроил, но каждая будет иметь свой тип.

2020-04-23 11:42 UTC, devality requested changes

2020-04-23 11:42 UTC, devality commented on test/factories/tasks.rb
> +  end
Ты запускал код? Тесты прошли? Помоему как минимум из-за этого не могли проходить.

2020-04-25 19:25 UTC, pn-y requested changes

2020-04-25 19:25 UTC, pn-y commented on test/factories/users.rb
> +    factory :admin_users, traits:[:admin]
Множественное число тут не нужно. 
Можно сократить просто до admin, developer, manager

2020-04-26 08:18 UTC, Sad1lovbatya commented
При таком именовании "Можно сократить просто до admin, developer, manager" 
у меня возникала ошибка  Factory already registered: admin (FactoryBot::DuplicateDefinitionError)

2020-04-27 09:09 UTC, pn-y requested changes

2020-04-27 09:09 UTC, pn-y commented on test/factories/admins.rb
> +  factory :admin, parent: :user do
А вот поэтому и была ошибка у тебя.
У тебя фабрики созданы отдельные. При том сейчас они не правильные. 
Давай в них вынесешь type соответствующий, и можно будет удалить специфичные трейты и фабрики из юзера.
Т.е. `create(:admin)` будет возвращать нового админа, но при этом основные атрибуты брать у юзера

2020-04-28 12:37 UTC, pn-y approved these changes

2020-05-01 07:37 UTC, merged