create test developer controller
Sad1lovbatya/TaskManager pull request #19
Opened 2020-04-28 15:45 UTC by Sad1lovbatya

2020-04-28 15:49 UTC, Sad1lovbatya commented
Посмотрел через byebug данные созданные для девелопера, но достать их для проверки создания юзера не смог, получилось достать только перенаправление body
Корректна ли будет моя проверка на nil девелопера?

2020-04-29 14:06 UTC, Andrew8xx8 requested changes

2020-04-29 14:06 UTC, Andrew8xx8 commented on app/controllers/web/developers_controller.rb
> +    def new
Форматирование неправильное

2020-04-29 14:32 UTC, Sad1lovbatya commented on app/controllers/web/developers_controller.rb
> +    def new
Поправил

2020-04-30 08:43 UTC, Andrew8xx8 commented
AuthHelper еще должен быть и настройка аутентификации

2020-04-30 09:28 UTC, Sad1lovbatya commented
> AuthHelper еще должен быть и настройка аутентификации

Добавил в прошлом пулреквесте, требовалось для проверки тестов создания сессии

2020-04-30 21:46 UTC, Andrew8xx8 approved these changes

2020-05-01 07:44 UTC, merged