Feature/api
Sad1lovbatya/TaskManager pull request #24
Opened 2020-05-08 04:29 UTC by Sad1lovbatya

2020-05-09 04:07 UTC, mkalmykov requested changes

2020-05-09 04:07 UTC, mkalmykov commented on app/responders/json_responder.rb
> +  end
Нужно отформатировать файл с помощью рубокопа.

2020-05-09 04:07 UTC, mkalmykov commented on config/initializers/active_model_serializer.rb
> +ActiveModelSerializers.config.adapter = ActiveModelSerializers::Adapter::JsonApi
По заданию адаптер должен быть другим: https://learn.dualboot.ru/lessons/7/practice/5. json и json api отличаются.

2020-05-09 04:07 UTC, mkalmykov commented on config/routes.rb
> +      resources :tasks, only: %i[index show create update destroy]
Нужно влить обновлённый конфиг рубокопа, который добавили вчера и отформатировать файлы с ним.

2020-05-09 04:07 UTC, mkalmykov commented on test/controllers/api/v1/tasks_controller_test.rb
> +    assert created_task.present?
Эта проверка имеет смысл только если `created_task` будет искаться с помощью `find_by`, потому что `find` кинет исключение, если не найдёт.

2020-05-09 04:07 UTC, mkalmykov commented on test/controllers/api/v1/tasks_controller_test.rb
> +    sign_in(author)
Мы логиним юзера для этого метода, а для других нужно?

2020-05-09 04:07 UTC, mkalmykov commented on test/controllers/api/v1/tasks_controller_test.rb
> +    author = create :user
Эта строка одинакова почти для всех кейсов. То, что должно быть везде, можно вынести в метод `setup`.

2020-05-09 04:07 UTC, mkalmykov commented on test/controllers/api/v1/tasks_controller_test.rb
> +    get :index, params: { format: :json }
Без создания хотя бы одной таски тест-кейс не имеет смысла, потому что будет пропущен целый блок в шаблоне, где потенциально могут быть ошибки.

2020-05-09 04:07 UTC, mkalmykov commented on test/controllers/api/v1/tasks_controller_test.rb
> +    assert_equal task_attributes.stringify_keys, created_task.slice(*task_attributes.keys)
Этот ассерт точно проходит?

2020-05-09 04:07 UTC, mkalmykov commented on test/controllers/api/v1/tasks_controller_test.rb
> +    assert !Task.where(id: task.id).exists?
Вместо `assert !<smth>` можно писать `refute <smth>`.

2020-05-09 04:07 UTC, mkalmykov commented on test/controllers/api/v1/tasks_controller_test.rb
> +    assert !Task.where(id: task.id).exists?
Кроме того, метод `exists?` тоже принимает параметры: `Task.exists?(task.id)`.

2020-05-09 09:46 UTC, Sad1lovbatya commented on test/controllers/api/v1/tasks_controller_test.rb
> +    assert !Task.where(id: task.id).exists?
Поправил все замечания, тесты проходят, на localhost тоже api доступна
Извиняюсь, в пуллреквест попали все исправления рубокопа в ветке
можно ли как-то сделать так чтобы в пуллреквесте не показывались некоторые изменения
Как я понимаю, при удалении коммита и добавлении нового,
мусора в Files changes стало бы ещё больше?

2020-05-10 16:48 UTC, artempartos commented on test/controllers/api/v1/tasks_controller_test.rb
> +    assert !Task.where(id: task.id).exists?
Первый раз обычно линтер фиксится в отдельном PR 
Но ок, ничего страшного.

2020-05-10 16:48 UTC, artempartos commented
👍

2020-05-11 06:30 UTC, merged