Generate models
Sad1lovbatya/TaskManager pull request #5
Opened 2020-04-15 10:37 UTC by Sad1lovbatya

2020-04-15 12:05 UTC, Sad1lovbatya commented
Возникла ошибка при создании пользователей и задач в консоли rails, испрашивал файлы в db/schema.rb с пощью добавления новый миграций, всё заработало
сделал в ветке generate_models, валидация попала сюда тоже

2020-04-15 12:47 UTC, artempartos requested changes

2020-04-15 12:47 UTC, artempartos commented on test/factories/tasks.rb
> +  factory :task do
давай сделаем seqeunces для каждого поля
ассоциации по умолчанию оставим nil
https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#sequences

2020-04-15 12:47 UTC, artempartos commented on test/models/manager_test.rb
> +class ManagerTest < ActiveSupport::TestCase
удалить неиспользуемые файлы

2020-04-15 12:47 UTC, artempartos commented on test/test_helper.rb
>    fixtures :all
удалить загрузку фикстур

2020-04-15 13:27 UTC, Sad1lovbatya commented on test/factories/tasks.rb
> +  factory :task do
seqeunces сделать прям в файле tasks.rb или создать новый файл seqeunces.rb?

2020-04-15 14:08 UTC, artempartos commented on test/factories/tasks.rb
> +  factory :task do
в отдельный файл, их можно шарить между фабриками

2020-04-15 14:27 UTC, Sad1lovbatya commented on test/factories/tasks.rb
> +  factory :task do
https://github.com/Sad1lovbatya/TaskManager/commit/b61a4ce630943fc405d0aa6e291b19a39574eee2 
Добавил sequences, но не совсем понял зачем они нужны 
и как они должны выглядеть конкретно в этой задаче
Генерация и подсчёт возможных значений моих полей?

2020-04-15 17:51 UTC, artempartos requested changes

2020-04-15 17:51 UTC, artempartos commented on test/factories/seqeunces.rb
> +    "author_id #{n}"
это ассоциации, и тут айдишник, не нужно ассоциации в сиквенсы

2020-04-15 17:51 UTC, artempartos commented on test/factories/seqeunces.rb
> +  sequence :state do |n|
стейт должен браться из стейт машины

2020-04-15 17:51 UTC, artempartos commented on test/factories/tasks.rb
> +    name { 'MyString' }
убрать здесь все блоки { }
он по умолчанию будет брать из сиквенсов если они есть с таким же именем

2020-04-15 17:51 UTC, artempartos commented on test/models/task_test.rb
> +class TaskTest < ActiveSupport::TestCase
удалить неиспользуемые файлы. все

2020-04-15 18:11 UTC, Sad1lovbatya commented on test/factories/seqeunces.rb
> +    "author_id #{n}"
https://github.com/Sad1lovbatya/TaskManager/commit/60e0be7d1bb98e92513e9a352f3e29666bf0491e 
Исправил sequence

2020-04-16 06:29 UTC, Sad1lovbatya commented on test/factories/seqeunces.rb
> +    "author_id #{n}"
Как я понимаю sequence генерирует значения полей в базу данных для проверки успешной работы тестов, верно?

2020-04-16 07:56 UTC, aelaa commented on app/models/task.rb
> +
rubocop не ругнулся на пустые строки?

2020-04-16 07:58 UTC, Sad1lovbatya commented on app/models/task.rb
> +
Прогонял через него не заметил, ещё раз проверю сейчас

2020-04-16 07:59 UTC, aelaa commented on config/database.yml
> +  database: <%= ENV['DATABASE_NAME'] || 'task_manager_development' %>
это же другое задание? а как оно оказалось в этом реквесте?

2020-04-16 09:18 UTC, Sad1lovbatya commented on config/database.yml
> +  database: <%= ENV['DATABASE_NAME'] || 'task_manager_development' %>
это должно уже было быть в этой ветке, но добавилось при этом  пуллреквесте
мне лучше  закрыть этот пулреквест и создать новый, со всеми верными изменениями?

2020-04-16 09:21 UTC, aelaa commented on config/database.yml
> +  database: <%= ENV['DATABASE_NAME'] || 'task_manager_development' %>
Странно как оно сюда попало. Ты создавал ветку generate_models от ветки, в которой выполнял другое задание?

2020-04-16 09:24 UTC, Sad1lovbatya commented on config/database.yml
> +  database: <%= ENV['DATABASE_NAME'] || 'task_manager_development' %>
да, создавал ветку  generate_models  от ветки задания до этого

2020-04-16 09:25 UTC, aelaa commented on config/database.yml
> +  database: <%= ENV['DATABASE_NAME'] || 'task_manager_development' %>
в принципе логично, без базы модели не создашь, но надо теперь привести это в порядок. Ты уже смержил ветку, от которой создавал эту?

2020-04-16 09:31 UTC, Sad1lovbatya commented on config/database.yml
> +  database: <%= ENV['DATABASE_NAME'] || 'task_manager_development' %>
Да, уже выполнил мерж  
У меня в ветке develop файл database.yml такой же, если я сейчас смержу( при условии, что остальное в этой ветке верно) ветку generate_models в develop, не будет ли всё верно?

2020-04-16 09:33 UTC, Sad1lovbatya commented on app/models/task.rb
> +
У меня rubocop проверяет и исправляет код, но выводится такое предупреждение
Как я понимаю, у меня не работают настройки, которые я добавил в файл rubocop.yml?

The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file:
 - Lint/RaiseException (0.81)
 - Lint/StructNewOverride (0.81)
 - Style/HashEachMethods (0.80)
 - Style/HashTransformKeys (0.80)
 - Style/HashTransformValues (0.80)
For more information: https://docs.rubocop.org/en/latest/versioning/

2020-04-16 09:37 UTC, aelaa commented on app/models/task.rb
> +
за пустые строки отвечает Layout/EmptyLines. Не уверен работает ли он по дефолту, попробуй проверить

2020-04-16 09:39 UTC, aelaa commented on config/database.yml
> +  database: <%= ENV['DATABASE_NAME'] || 'task_manager_development' %>
Если бы Github видел такой же файл в develop, он бы не показал этот diff, притом что этот реквест у тебя тоже в develop. Кажется с ним что-то не так, и я не уверен что произойдет если ты его попробуешь смержить

2020-04-16 09:42 UTC, aelaa commented on config/database.yml
> +  database: <%= ENV['DATABASE_NAME'] || 'task_manager_development' %>
вообще в такой ситуации есть 2 варианта:
- пересоздать реквест и черрипикнуть коммиты отсюда, по пути решая конфликты если они есть
- сделать rebase от develop. Не советую, без опыта можно напортачить)

2020-04-16 09:55 UTC, Sad1lovbatya commented on config/database.yml
> +  database: <%= ENV['DATABASE_NAME'] || 'task_manager_development' %>
Спасибо, пересоздам реквест, попробую всё решить)
У меня возникла такая  проблема с Git, сейчас я перешёл в ветку девелоп и гит  не выпускает из неё, не довавив в неё все untracked files, которые я изменил в ветке generate_models(хотя они все были уже закоммичены)
 из-за чего такое может случаться?
Как я понимаю работу git,  в ветке  generate_models, все мой файлы были закоммичены и ветка без изменений, при переходе в девелоп, я возвращаюсь к той версии без всех изменений в остальных ветках( кроме тех которые я уже смержил), а сейчас моё понимание сломалось

2020-04-16 09:58 UTC, Sad1lovbatya commented on config/database.yml
> +  database: <%= ENV['DATABASE_NAME'] || 'task_manager_development' %>
Я могу решить эту проблему так, удалить локально мой репозиторий, скачать его занаво 
И там сделать изменения для нового пуллреквеста?

2020-04-16 10:01 UTC, aelaa commented on config/database.yml
> +  database: <%= ENV['DATABASE_NAME'] || 'task_manager_development' %>
лучше разобраться в проблеме сейчас, чтобы потом каждый раз не пересоздавать
ты уверен, что они были закоммичены? Ты сделал git pull на develop после мержа прошлого реквеста?

2020-04-16 10:06 UTC, Sad1lovbatya commented on config/database.yml
> +  database: <%= ENV['DATABASE_NAME'] || 'task_manager_development' %>
да, в этом видимо  проблема, git pull после мержа я не делал
спасибо)

2020-04-16 10:53 UTC, closed without merging

2020-04-16 11:17 UTC, Sad1lovbatya commented on config/database.yml
> +  database: <%= ENV['DATABASE_NAME'] || 'task_manager_development' %>
Всё исправил, удалил последний коммит и поменял
Можешь, пожалуйста, посмотреть новый пуллреквест  
https://github.com/Sad1lovbatya/TaskManager/pull/8